#!/bin/bash
cat /var/log/apache2/access.log | uniq | grep -v "192.168.0.1" | grep -v "POST"|tail -n60 | cut -d ' ' -f 1-7 > /var/www/html/access.log

cat /var/log/apache2/access.log | grep -v "192.168.0.1" | grep -v "POST" | cut -d ' ' -f 1 | uniq --check-chars=8 > /root/scripts/ip.list

#cat /var/log/apache2/access.log.1 | grep -v "192.168.0.1" | grep -v "POST" | cut -d ' ' -f 1 | uniq --check-chars=8 > /root/scripts/ip.list.old

