#!/usr/bin/env python3.7
import requests
import json
ip_list = open("/root/scripts/ip.list", "r")
located = open("/root/scripts/coordinate.list","w")
line = ip_list.readline()
while line:
    ip = line.replace('\n','')
    url = 'https://ipvigilante.com/json/'
    default = '/default'
    url = url+ip+default
    rawdata = requests.get(url).text
    rawdata = json.loads(rawdata)
    rawdata = rawdata['data']
    lati = rawdata['latitude']
    longi = rawdata['longitude']
    x = {'lat':lati,'long':longi}
    located.write(str(x))
    located.write('\n')
    #print(x)
    line = ip_list.readline()
ip_list.close()
located.close()
