#!/usr/bin/env python3.7
import requests
import json
import sys
import os
from datetime import datetime

dynhtml = open("/var/www/html/access_log.html","w")
page = """
<!DOCTYPE html>
<html lang="de">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="/access_log.css" media="screen" />
<title>Access Log</title>
<link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/GNOME_Terminal_icon_2019.svg/2000px-GNOME_Terminal_icon_2019.svg.png">

</head>
<body class="background" style="font-family:comic-sans">

<div class="navbar a" width="5000px" background-color=green>
        <a href="/">Home</a>
        <a href="/admin/index.php">Pihole</a>
        <a href="/index-css.css">Nextcloud</a>
        <a href="https://flexonmyex.de:4200">Shell</a>
        <a href="/access_log">Access Log</a>


</div>

<div>
<p>Updatet at: {}</p>
</div>

<div id="text" class="text">

        <p>&nbsp;</p>
        <p style="font-size:40pt" style="font-family:Courier" align="center"><u>Todays Visitors :</u></p>
</div>
<div id="text" class="text">

        <p>&nbsp;</p>
        <p style="font-size:30pt">Where they are from :</p>
</div>

<div id="list" class="text">
  <p class="text" style="font-size:30pt">
     <iframe src="ip_located.list" frameborder="0" height="100%" width="100%" class="text" align="left">
     </iframe>
  </p>
</div>
<div id="map">
     <iframe src="map.html" frameborder="0" height="500px" width="100%" align="right">
     </iframe>
</div>

<div id="text" class="text">

        <p>&nbsp;</p>
        <p style="font-size:30pt">What they want :</p>
</div>


<div id="list" class="text">
  <p class="text" style="font-size:30pt">
     <iframe src="access.log" frameborder="0" height="500px" width="100%" class="text" align="right">
     </iframe>
  </p>
</div>





</body>
</html>"""

page = page.format(datetime.now())

dynhtml.write(page)
print("HTML created")
dynhtml.close()
