#!/usr/bin/env python3.7
import requests
import json
import sys
import os

args = sys.argv[1:]
modt = str(args[0])
#print(modt)

dynindex = open("/var/www/html/index.html","w")

page = """
<!DOCTYPE html>
<html lang="de">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="/index.css" media="screen" />
<title>Raspberry Pi</title>
<link rel="icon" href="https://img.icons8.com/carbon-copy/2x/instagram-new.png">

</head>
<body class="background">

<div class="navbar" width="5000px" background-color=green>
        <a href="/">Home</a>
        <a href="/admin/index.php">Pihole</a>
        <a href="/index-css.css">Nextcloud</a>
        <a href="https://flexonmyex.de:4200">Shell</a>
        <a href="/access_log.html">Access Log</a>


</div>



<pre class="Atari">



   /:` ;: `:\        :::.:::::::::::::::.    :::::::..   :::
   /;` ;; `;\       ;;`;;;;;;;;;;'''';;`;;   ;;;;``;;;;  ;;;
   n[' [[ '[n      ,[[ '[[,   [[    ,[[ '[[,  [[[,/[[['  [[[
  c$"  $$  "$c    c$$$cc$$$c  $$   c$$$cc$$$c $$$$$$c    $$$
 o8"   88   "8o    888   888, 88,   888   888,888b "88bo,888
mM"    MM    "Mm   YMM   ""`  MMM   YMM   ""` MMMM   "W" MMM

</pre>

<div class="banner">
    <h1>{}</h1>
</div>


</body>
</html>"""

page = page.format(modt)

dynindex.write(page)

print("HTML created")
dynindex.close()
