#!/usr/bin/env python3.7
import requests
import json
ip_list = open("/root/scripts/ip.list", "r")
located = open("/var/www/html/ip_located.list","w")
line = ip_list.readline()
while line:
    ip = line.replace('\n','')
    url = 'https://ipvigilante.com/json/'
    default = '/default'
    url = url+ip+default
    rawdata = requests.get(url).text

    rawdata = json.loads(rawdata)
    rawdata = rawdata['data']
    country = rawdata['country_name']
    city = rawdata['city_name']
    lati = rawdata['latitude']
    longi = rawdata['longitude']

    located.write('IPv4 -->  '+str(ip)+'   '+str(country)+','+str(city)+'   '+str(lati)+' '+str(longi))
    located.write('\n')
    #print('IPv4 -->  '+str(ip)+'   '+str(country)+','+str(city)+'   '+str(lati)+' '+str(longi))
    line = ip_list.readline()
ip_list.close()
located.close()
